import { Inter } from 'next/font/google'
import "../../app/globals.css"
import { getServerSession } from 'next-auth'
import { authOptions } from '../api/auth/[...nextauth]/route'
import { redirect } from 'next/navigation'
import Image from 'next/image'
import AppSidebar from '@/components/layout/AppSidebar'
import localFont from 'next/font/local'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const headingFont = localFont({
  src: '../../../public/fonts/font.woff2'
})

export default async function AppLayout({ children }) {

  const session = await getServerSession(authOptions)

  if(!session) {
    redirect('/')
  }



  return (
    
    <html lang="en">
      <body className={headingFont.className + 'bg-gray-100'}>
        <main className='flex min-h-screen'>
            <aside className='bg-white w-52 rounded-3xl shadow-[rgba(0,0,15,0.5)_10px_5px_4px_0px] p-4 '>
                <div className='rounded-full overflow-hidden aspect-square w-24 mx-auto'>
                  <Image src={session.user.image} alt='avatar' width={256} height={256} />
                </div>
                <AppSidebar />
            </aside>
            <div className='grow'>
              <div className='bg-white m-8 p-4 shadow'>
        {children}
        </div>
        </div>
        </main>
        </body>
    </html>
  )
}
