import { Inter } from 'next/font/google'
import './globals.css'
import { Roboto } from 'next/font/google'
import Header from '../../components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = ({
  subsets: ['latin'],
  weight: ['1000', '1000'],
})

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={roboto.className}>
        <main>
          <Header />
        {children}
        </main>
        </body>
    </html>
  )
}
